# Change these first
owner: EthanSuperior # Your GitHub organization or username, where this repository lives
repo: jwt-pizza-status # The name of this repository

sites:
  - name: JWT-Pizza
    url: https://pizza.evankchase.click/
  - name: JWT-Pizza (DEV)
    url: https://stage-pizza.evankchase.click/
  - name: JWT-Pizza-Service
    url: https://pizza-service.evankchase.click/
  - name: JWT-Pizza-Factory
    url: https://pizza-factory.cs329.click

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: pizza-status.evankchase.click
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/devops329/jwt-pizza/main/public/jwt-pizza-logo.png
  name: JWT Pizza Status
  introTitle: "**JWT Pizza** is a pizza buying service made by the BYU CS329 team."
  introMessage: This is a simple satus page displaying the up time of the JWT-Pizza service, made using [upptime](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
